# Generated by Django 4.2.11 on 2024-05-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwork',
            options={'verbose_name': 'film', 'verbose_name_plural': 'films'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={
                'verbose_name': 'genre_film',
                'verbose_name_plural': 'genres_film',
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={
                'verbose_name': 'film_person',
                'verbose_name_plural': 'film_persons',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.FileField(
                blank=True, null=True, upload_to='movies/', verbose_name='file'
            ),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='person',
            field=models.ManyToManyField(
                through='movies.PersonFilmwork', to='movies.person'
            ),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='created'
            ),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='created'
            ),
        ),
        migrations.AlterField(
            model_name='genre',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name_genre'),
        ),
        migrations.AlterField(
            model_name='genrefilmwork',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='created'
            ),
        ),
        migrations.AlterField(
            model_name='person',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='created'
            ),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='created'
            ),
        ),
    ]
