# Generated by Django 4.2.11 on 2024-05-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_filmwork_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmwork',
            old_name='person',
            new_name='persons',
        ),
    ]
