# Generated by Django 4.2.11 on 2024-05-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_person_filmwork_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(
                choices=[
                    ('ac', 'actor'),
                    ('sc', 'screenwriter'),
                    ('mg', 'manager'),
                ],
                max_length=100,
                verbose_name='role',
            ),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(
                fields=['creation_date', 'type', 'rating'],
                name='film_creation_date_type_rating',
            ),
        ),
    ]
