# Generated by Django 4.2.11 on 2024-05-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_personfilmwork_role_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(
                fields=['film_work_id', 'person_id', 'role'],
                name='film_person_role_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(
                fields=('film_work_id', 'person_id', 'role'),
                name='film_person_role',
            ),
        ),
    ]
