# Generated by Django 4.2.11 on 2024-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_personfilmwork_film_person_role_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='genrefilmwork',
            index=models.Index(
                fields=['film_work_id', 'genre_id'], name='film_genre_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(
                fields=('film_work_id', 'genre_id'), name='film_genre'
            ),
        ),
    ]
