version: '3'
services:
  django: 
      build:  .
      env_file:
        - config/env/.env
  postgres:
      image: postgres:16.0
      restart: always
      env_file:
        - config/env/bd.env
      volumes:
        - pgdata:/var/lib/postgresql/data
  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./site_conf:/etc/nginx/conf.d:ro
        - ./staticfiles:/var/staticfiles:ro
      depends_on:
        - django
      ports:
        - "80:80"
volumes:
  pgdata:
    
